import { EmployeePayrollDetails, EmployeeEthinicGroup } from './employee.model';
import { EmployeeJobDetails } from './../job/models/job-details.model';

export class EmployeeFullEntity {
        Id: string;
        Title: string;
        FirstName: string;
        MiddleName: string;
        Surname: string;
        KnownAs: string;
        PreviousName: string;
        Type: string;
        DOB?: Date;
        Email: string;
        PersonalEmail: string;
        UserId: string;
        Gender: number;
        User: any;
        IsPrimaryContact: boolean;
        AddressId: string;
        Address: any;
        Job: EmployeeJobDetails;
        IsLeaver: boolean;
        PictureId: string;
        VehicleDetails: Array<any>;
        IsEmployee: boolean;
        Nationality: string;
        EmployeeNumber: string;
        EmergencyContacts: Array<any>;
        BankDetails: Array<any>;
        EducationDetails: Array<any>;
        TrainingDetails: Array<any>;
        PreviousEmploymentDetails: Array<any>;
        JobHistoryDetails: Array<any>;
        SalaryHistoryDetails: Array<any>;
        EthnicGroup: EmployeeEthinicGroup;
        EmploymentType: any;
        EmploymentTypeId: string;
        EmployeePayrollDetails: EmployeePayrollDetails;
        EmployeeGroups: Array<any>;
        CompanyId: string;
        EmployeeProtectiveCategoriesGrp: Array<any>;
        Events: Array<any>;
        HasEmail: boolean;
        Age: string;
        UserPassword: string;
        CreateUser: boolean;
        UserName: string;
        ConfirmPassword: string;
        EmpEmailUser: string;
        constructor() {
                this.Id = "";
                this.Title = "";
                this.FirstName = "";
                this.MiddleName = "";
                this.Surname = "";
                this.KnownAs = "";
                this.PreviousName = "";
                this.Type = "";
                this.DOB = null;
                this.Email = "";
                this.PersonalEmail = "";
                this.UserId = "";
                this.Gender = null;
                this.User = null;
                this.IsPrimaryContact = false;
                this.AddressId = "";
                this.Address = null;
                this.Job = new EmployeeJobDetails();
                this.IsLeaver = false;
                this.PictureId = "";
                this.VehicleDetails = [];
                this.IsEmployee = false;
                this.Nationality = "";
                this.EmployeeNumber = "";
                this.EmergencyContacts = [];
                this.BankDetails = [];
                this.EducationDetails = [];
                this.TrainingDetails = [];
                this.PreviousEmploymentDetails = [];
                this.JobHistoryDetails = [];
                this.SalaryHistoryDetails = [];
                this.EthnicGroup = new EmployeeEthinicGroup();
                this.EmploymentType = null;
                this.EmploymentTypeId = "";
                this.EmployeePayrollDetails = new EmployeePayrollDetails();
                this.EmployeeGroups = null;
                this.CompanyId = "";
                this.EmployeeProtectiveCategoriesGrp = [];
                this.Events = [];
                this.HasEmail = false;
                this.Age = "";
                this.UserPassword = "";
                this.CreateUser = false;
                this.UserName = '';
                this.ConfirmPassword = '';
                this.EmpEmailUser = '';
        }
}